# Generated by Django 4.1.6 on 2023-02-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
