# Generated by Django 4.1.6 on 2023-02-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('story', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='movies_pics')),
                ('released', models.IntegerField(blank=True)),
            ],
        ),
    ]
