# Generated by Django 4.1.6 on 2023-02-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshopping_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='e_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'e_cart',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='e_cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_status', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopping_cart_app.e_cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopping_app.products_db')),
            ],
            options={
                'db_table': 'e_cart_item',
            },
        ),
    ]
